### PR TITLE
Resolve: You cannot cancel multiple marks at the same time in a paragraph where there are already multiple marks

### PR DESCRIPTION
**Pull request by littersnaker**
… where there are already multiple marks

### CODE REVIEW

**Comment by marijnh** [comment]
This change looks very suspicious. You're going to have to at least describe the problem you're trying to solve here properly.

**Comment by littersnaker** [comment]
This branch solves the problem that only one of the marks will be canceled when clicking on the corresponding mark in the middle of the field that has been underlined and bolded italics on the official website

**Comment by marijnh** [comment]
That's still not very specific. The way I understand it is you've made some bold+italic text in the demo on the website, put the cursor in there, and click off the buttons for bold and italic in the menu bar. If I do that and then type, I get plain, unmarked text.

**Comment by littersnaker** [comment]
I just tried the operation I mentioned on the official website and indeed obtained a plain text font. However, in the Tiptap project, we can only cancel one of the marks before. We may need to wait for them to update the version before looking at it. I will merge and close this first. Thank you for your reply

**Pull request closed without merging**
